// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Go_skeleton/internal/biz"
	"Go_skeleton/internal/data"
	"Go_skeleton/internal/service"
	"Go_skeleton/pkg/app"
	"Go_skeleton/pkg/config"
	"Go_skeleton/pkg/server"
)

// Injectors from wire.go:

func initApp(cfg *config.Config) (*AppContainer, func(), error) {
	serverConfig := config.NewServerConfig(cfg)
	restServer := server.NewRestServer(serverConfig)
	rpcServer := server.NewRpcServer(serverConfig)
	appApp := app.NewApp(restServer, rpcServer)
	userRepo := data.NewUserRepo()
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	appContainer := &AppContainer{
		App:         appApp,
		UserService: userService,
	}
	return appContainer, func() {
	}, nil
}
